# Site settings
title: Pointing to the Moon
description: Blog of  Yin Huang
baseurl: "" 
url: "https://a1iez.github.io/" 

# GitHub User settings
username: Yin Huang
github_username: A1iez
user_description: A Physics undergrad with a broad interest
user_title: Physics Undergraduate
email: huang_yin@student.smc.edu

# Blog Author settings
author:
  name:           Yin Huang
  picture:        
  email:         huang_yin@student.smc.edu
  description:    I'm a Physics undergrad with a broad interest.
  twitter:
  facebook:
  github:         https://a1iez.github.io
  linkedin:
  # # If you're forking this site, make sure you delete this entry!
  clustrmap:      
  # If you're forking this site, make sure you delete this entry!


# markdown
markdown: kramdown

future: true
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
 - "*.source.*"
